overrides:
  "volar-service-yaml@0.0.70>yaml-language-server@1.20.0": "~1.22.0"
ignoredOptionalDependencies:
  - "sharp"
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: true
blockExoticSubdeps: true
dedupePeers: true
strictPeerDependencies: true
allowBuilds:
  esbuild: true
