name = 'nullfire'
pages_build_output_dir = './dist'
compatibility_date = '2025-05-05'
compatibility_flags = []
send_metrics = false
keep_vars = true
workers_dev = false

[build]
command = "pnpm run build --mode production"

[assets]
directory = './dist/'
html_handling = 'force-trailing-slash'
not_found_handling = 'none'

[vars]
ASTRO_TELEMETRY_DISABLED = '1'
NODE_ENV = 'production'
MODE = 'production'
PROD = 'true'
DEV = 'false'
