name: "Build and Deploy to GitHub Pages"

on:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!.github/**"
      - "!.vscode/**"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!.prettierignore"
      - "!.prettierrc"
      - "!CODEOWNERS"
      - "!README.md"
      - "!_outdated.txt"
      - ".github/workflows/build_deploy.yml"
  workflow_dispatch:

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

env:
  NODE_ENV: "production"
  MODE: "production"
  PROD: true
  DEV: false
  ASTRO_TELEMETRY_DISABLED: 1
  SITE_URL_OVERRIDE: "https://maxxusx.github.io/nullfire-site/"
  SITE_PATH_OVERRIDE: "/nullfire-site/"

defaults:
  run:
    shell: "bash"
    working-directory: "."

jobs:
  build:
    permissions:
      contents: "read"

    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup PNPM"
        uses: "pnpm/action-setup@v4"
        with:
          version: "10.12.4"
          package_json_file: "./package.json"

      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: "Install"
        run: "pnpm install --prod"

      - name: "Build"
        run: "pnpm run build --mode production"

      - name: "Upload Pages Artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./dist/"

  deploy:
    needs: "build"

    permissions:
      pages: "write"
      id-token: "write"

    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
