name: "Build in Development and Deploy to GitHub Pages"

on:
  workflow_dispatch:

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

env:
  NODE_ENV: "development"
  MODE: "development"
  PROD: false
  DEV: true
  ASTRO_TELEMETRY_DISABLED: 1
  SITE_URL_OVERRIDE: "https://maxxusx.github.io/nullfire-site/"
  SITE_PATH_OVERRIDE: "/nullfire-site/"

defaults:
  run:
    shell: "bash"
    working-directory: "."

jobs:
  build:
    permissions:
      contents: "read"

    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Setup PNPM"
        uses: "pnpm/action-setup@v4"
        with:
          package_json_file: "./package.json"

      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: "Install"
        run: "pnpm install --prod"

      - name: "Build"
        run: "pnpm run build --verbose --mode development"

      - name: "Upload Pages Artifact"
        uses: "actions/upload-pages-artifact@v4"
        with:
          path: "./dist/"

  deploy:
    needs: "build"

    permissions:
      pages: "write"
      id-token: "write"

    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
        with:
          error_count: "1"
