name: "Rebuild Lockfile"

on:
  workflow_dispatch:

concurrency:
  group: "rebuild-lockfile"
  cancel-in-progress: true

permissions:
  contents: "write"
  pull-requests: "write"

env:
  NODE_ENV: "development"
  CI: false

defaults:
  run:
    shell: "bash"
    working-directory: "."

jobs:
  rebuild_lockfile:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            package.json
            pnpm-lock.yaml
            .gitattributes

      - name: "Create branch"
        run: |
          git checkout -b rebuild-lockfile

      - name: "Setup PNPM"
        uses: "pnpm/action-setup@v5"
        with:
          package_json_file: "./package.json"

      - name: "Setup Node"
        uses: "actions/setup-node@v6"
        with:
          node-version-file: "./package.json"
          check-latest: true
          package-manager-cache: false

      - name: "Update Dependencies"
        run: "pnpm update"

      - name: "Delete node_modules"
        run: "rm -rf ./node_modules"

      - name: "Delete pnpm-lock.yaml"
        run: "rm -rf ./pnpm-lock.yaml"

      - name: "Install Dependencies"
        run: "pnpm install --no-frozen-lockfile"

      - name: "Dedupe Dependencies"
        run: "pnpm dedupe"

      - name: "Create PR"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          git add pnpm-lock.yaml
          git commit -m "rebuild lockfile"
          git push origin rebuild-lockfile --force
          gh pr create --fill
        env:
          GH_TOKEN: ${{ github.token }}
