name: "Test"
run-name: 'Test ${{ format(fromJSON(''{"push":"commit {0} by @{1}","pull_request":"PR #{2} by @{3}"}'')[github.event_name], github.event.head_commit.id, (github.event.pusher.username || github.actor), github.event.number, (github.event.pull_request.user.name || github.actor)) || format(''(ran by @{0})'', github.triggering_actor) }}'

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "**"
      - "!.github/**"
      - "!.vscode/**"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!.prettierignore"
      - "!.prettierrc"
      - "!CODEOWNERS"
      - "!README.md"
      - "!wrangler.toml"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "**"
      - "!.github/**"
      - "!.vscode/**"
      - "!.editorconfig"
      - "!.gitattributes"
      - "!.gitignore"
      - "!.prettierignore"
      - "!.prettierrc"
      - "!CODEOWNERS"
      - "!README.md"
      - "!wrangler.toml"
      - ".github/workflows/test.yml"
  workflow_dispatch:

permissions:
  contents: "read"

env:
  NODE_ENV: "production"
  MODE: "production"
  PROD: true
  DEV: false
  ASTRO_TELEMETRY_DISABLED: 1

defaults:
  run:
    shell: "bash"
    working-directory: "."

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Setup PNPM"
        uses: "pnpm/action-setup@v4"
        with:
          package_json_file: "./package.json"

      - name: "Setup Node"
        uses: "actions/setup-node@v5"
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: "Install Dependancies"
        run: "pnpm install --prod --frozen-lockfile"

      - name: "Test"
        run: "pnpm run test"
