name: Test

on:
  push:
    branches-ignore: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
          package_json_file: "./package.json"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install
        shell: "bash"
        working-directory: .
        run: pnpm install --prod

      - name: Test
        shell: "bash"
        working-directory: .
        run: ASTRO_TELEMETRY_DISABLED=1 pnpm run test
