name: Test
run-name: Test ${{ ( ( github.event_name == 'push' && format('commit {0} ({1}) by @{2}', github.event.head_commit.id, github.event.after, (github.event.pusher.username || github.actor)) ) || ( ( github.event_name == 'pull_request' && format('PR #{0} ({1} by @{2})', github.event.number, github.event.pull_request.title, (github.event.pull_request.user.name || github.actor)) ) || format('(ran by @{0})', github.triggering_actor) ) ) }} PLEAS JUST WORK BRO

on:
  push:
    paths:
      - "!.github"
      - "!.vscode"
      - "!.gitignore"
      - "!.prettierignore"
      - "!.prettierrc"
      - "!*.md"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "!.github"
      - "!.vscode"
      - "!.gitignore"
      - "!.prettierignore"
      - "!.prettierrc"
      - "!*.md"
      - ".github/workflows/test.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_ENV: production
  ASTRO_TELEMETRY_DISABLED: 1

defaults:
  run:
    shell: "bash"
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
          package_json_file: "./package.json"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install
        run: pnpm install --prod

      - name: Test
        run: pnpm run test
